config/routes.rb
Rails.application.routes.draw do
  resources :experiencia
  resources :curriculos
  resources :alunos
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/aluno.rb
class Aluno < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/curriculo.rb
class Curriculo < ApplicationRecord
  belongs_to :aluno
end

app/models/experiencium.rb
class Experiencium < ApplicationRecord
  belongs_to :curriculo
  belongs_to :aluno
end

app/controllers/alunos_controller.rb
class AlunosController < ApplicationController
  before_action :set_aluno, only: %i[ show edit update destroy ]

  # GET /alunos or /alunos.json
  def index
    @alunos = Aluno.all
  end

  # GET /alunos/1 or /alunos/1.json
  def show
  end

  # GET /alunos/new
  def new
    @aluno = Aluno.new
  end

  # GET /alunos/1/edit
  def edit
  end

  # POST /alunos or /alunos.json
  def create
    @aluno = Aluno.new(aluno_params)

    respond_to do |format|
      if @aluno.save
        format.html { redirect_to @aluno, notice: "Aluno was successfully created." }
        format.json { render :show, status: :created, location: @aluno }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alunos/1 or /alunos/1.json
  def update
    respond_to do |format|
      if @aluno.update(aluno_params)
        format.html { redirect_to @aluno, notice: "Aluno was successfully updated." }
        format.json { render :show, status: :ok, location: @aluno }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alunos/1 or /alunos/1.json
  def destroy
    @aluno.destroy
    respond_to do |format|
      format.html { redirect_to alunos_url, notice: "Aluno was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aluno
      @aluno = Aluno.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def aluno_params
      params.require(:aluno).permit(:nome, :telefone, :email, :curso, :cidade)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/curriculos_controller.rb
class CurriculosController < ApplicationController
  before_action :set_curriculo, only: %i[ show edit update destroy ]

  # GET /curriculos or /curriculos.json
  def index
    @curriculos = Curriculo.all
  end

  # GET /curriculos/1 or /curriculos/1.json
  def show
  end

  # GET /curriculos/new
  def new
    @curriculo = Curriculo.new
  end

  # GET /curriculos/1/edit
  def edit
  end

  # POST /curriculos or /curriculos.json
  def create
    @curriculo = Curriculo.new(curriculo_params)

    respond_to do |format|
      if @curriculo.save
        format.html { redirect_to @curriculo, notice: "Curriculo was successfully created." }
        format.json { render :show, status: :created, location: @curriculo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @curriculo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /curriculos/1 or /curriculos/1.json
  def update
    respond_to do |format|
      if @curriculo.update(curriculo_params)
        format.html { redirect_to @curriculo, notice: "Curriculo was successfully updated." }
        format.json { render :show, status: :ok, location: @curriculo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @curriculo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /curriculos/1 or /curriculos/1.json
  def destroy
    @curriculo.destroy
    respond_to do |format|
      format.html { redirect_to curriculos_url, notice: "Curriculo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_curriculo
      @curriculo = Curriculo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def curriculo_params
      params.require(:curriculo).permit(:idiomas, :formacao, :conhecimentos, :outros, :aluno_id)
    end
end

app/controllers/experiencia_controller.rb
class ExperienciaController < ApplicationController
  before_action :set_experiencium, only: %i[ show edit update destroy ]

  # GET /experiencia or /experiencia.json
  def index
    @experiencia = Experiencium.all
  end

  # GET /experiencia/1 or /experiencia/1.json
  def show
  end

  # GET /experiencia/new
  def new
    @experiencium = Experiencium.new
  end

  # GET /experiencia/1/edit
  def edit
  end

  # POST /experiencia or /experiencia.json
  def create
    @experiencium = Experiencium.new(experiencium_params)

    respond_to do |format|
      if @experiencium.save
        format.html { redirect_to @experiencium, notice: "Experiencium was successfully created." }
        format.json { render :show, status: :created, location: @experiencium }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @experiencium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /experiencia/1 or /experiencia/1.json
  def update
    respond_to do |format|
      if @experiencium.update(experiencium_params)
        format.html { redirect_to @experiencium, notice: "Experiencium was successfully updated." }
        format.json { render :show, status: :ok, location: @experiencium }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @experiencium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /experiencia/1 or /experiencia/1.json
  def destroy
    @experiencium.destroy
    respond_to do |format|
      format.html { redirect_to experiencia_url, notice: "Experiencium was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_experiencium
      @experiencium = Experiencium.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def experiencium_params
      params.require(:experiencium).permit(:empresa, :cargo, :descricao, :dataInicio, :dataFim, :curriculo_id, :aluno_id)
    end
end

app/helpers/alunos_helper.rb
module AlunosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/curriculos_helper.rb
module CurriculosHelper
end

app/helpers/experiencia_helper.rb
module ExperienciaHelper
end

app/views/alunos/_form.html.erb
<%= form_with(model: aluno) do |form| %>
  <% if aluno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(aluno.errors.count, "error") %> prohibited this aluno from being saved:</h2>

      <ul>
        <% aluno.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :telefone %>
    <%= form.text_field :telefone %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :curso %>
    <%= form.text_field :curso %>
  </div>

  <div class="field">
    <%= form.label :cidade %>
    <%= form.text_field :cidade %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/alunos/edit.html.erb
<h1>Editing Aluno</h1>

<%= render 'form', aluno: @aluno %>

<%= link_to 'Show', @aluno %> |
<%= link_to 'Back', alunos_path %>

app/views/alunos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Alunos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Telefone</th>
      <th>Email</th>
      <th>Curso</th>
      <th>Cidade</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alunos.each do |aluno| %>
      <tr>
        <td><%= aluno.nome %></td>
        <td><%= aluno.telefone %></td>
        <td><%= aluno.email %></td>
        <td><%= aluno.curso %></td>
        <td><%= aluno.cidade %></td>
        <td><%= link_to 'Show', aluno %></td>
        <td><%= link_to 'Curriculos', curriculos_path %></td>
        <td><%= link_to 'Edit', edit_aluno_path(aluno) %></td>
        <td><%= link_to 'Destroy', aluno, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Aluno', new_aluno_path %>

app/views/alunos/new.html.erb
<h1>New Aluno</h1>

<%= render 'form', aluno: @aluno %>

<%= link_to 'Back', alunos_path %>

app/views/alunos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @aluno.nome %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @aluno.telefone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @aluno.email %>
</p>

<p>
  <strong>Curso:</strong>
  <%= @aluno.curso %>
</p>

<p>
  <strong>Cidade:</strong>
  <%= @aluno.cidade %>
</p>

<%= link_to 'Edit', edit_aluno_path(@aluno) %> |
<%= link_to 'Back', alunos_path %>

app/views/curriculos/_form.html.erb
<%= form_with(model: curriculo) do |form| %>
  <% if curriculo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(curriculo.errors.count, "error") %> prohibited this curriculo from being saved:</h2>

      <ul>
        <% curriculo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :idiomas %>
    <%= form.text_field :idiomas %>
  </div>

  <div class="field">
    <%= form.label :formacao %>
    <%= form.text_field :formacao %>
  </div>

  <div class="field">
    <%= form.label :conhecimentos %>
    <%= form.text_field :conhecimentos %>
  </div>

  <div class="field">
    <%= form.label :outros %>
    <%= form.text_field :outros %>
  </div>

  <div class="field">
    <%= form.label :aluno_id %>
    <%= form.text_field :aluno_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/curriculos/edit.html.erb
<h1>Editing Curriculo</h1>

<%= render 'form', curriculo: @curriculo %>

<%= link_to 'Show', @curriculo %> |
<%= link_to 'Back', curriculos_path %>

app/views/curriculos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Curriculos</h1>

<table>
  <thead>
    <tr>
      <th>Idiomas</th>
      <th>Formacao</th>
      <th>Conhecimentos</th>
      <th>Outros</th>
      <th>Aluno</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @curriculos.each do |curriculo| %>
      <tr>
        <td><%= curriculo.idiomas %></td>
        <td><%= curriculo.formacao %></td>
        <td><%= curriculo.conhecimentos %></td>
        <td><%= curriculo.outros %></td>
        <td><%= curriculo.aluno_id %></td>
        <td><%= link_to 'Show', curriculo %></td>
        <td><%= link_to 'Edit', edit_curriculo_path(curriculo) %></td>
        <td><%= link_to 'Destroy', curriculo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Curriculo', new_curriculo_path %>

app/views/curriculos/new.html.erb
<h1>New Curriculo</h1>

<%= render 'form', curriculo: @curriculo %>

<%= link_to 'Back', curriculos_path %>

app/views/curriculos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Idiomas:</strong>
  <%= @curriculo.idiomas %>
</p>

<p>
  <strong>Formacao:</strong>
  <%= @curriculo.formacao %>
</p>

<p>
  <strong>Conhecimentos:</strong>
  <%= @curriculo.conhecimentos %>
</p>

<p>
  <strong>Outros:</strong>
  <%= @curriculo.outros %>
</p>

<p>
  <strong>Aluno:</strong>
  <%= @curriculo.aluno_id %>
</p>

<%= link_to 'Edit', edit_curriculo_path(@curriculo) %> |
<%= link_to 'Back', curriculos_path %>

app/views/experiencia/_form.html.erb
<%= form_with(model: experiencium) do |form| %>
  <% if experiencium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(experiencium.errors.count, "error") %> prohibited this experiencium from being saved:</h2>

      <ul>
        <% experiencium.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :empresa %>
    <%= form.text_field :empresa %>
  </div>

  <div class="field">
    <%= form.label :cargo %>
    <%= form.text_field :cargo %>
  </div>

  <div class="field">
    <%= form.label :descricao %>
    <%= form.text_field :descricao %>
  </div>

  <div class="field">
    <%= form.label :dataInicio %>
    <%= form.date_select :dataInicio %>
  </div>

  <div class="field">
    <%= form.label :dataFim %>
    <%= form.date_select :dataFim %>
  </div>

  <div class="field">
    <%= form.label :curriculo_id %>
    <%= form.text_field :curriculo_id %>
  </div>

  <div class="field">
    <%= form.label :aluno_id %>
    <%= form.text_field :aluno_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/experiencia/edit.html.erb
<h1>Editing Experiencium</h1>

<%= render 'form', experiencium: @experiencium %>

<%= link_to 'Show', @experiencium %> |
<%= link_to 'Back', experiencia_path %>

app/views/experiencia/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Experiencia</h1>

<table>
  <thead>
    <tr>
      <th>Empresa</th>
      <th>Cargo</th>
      <th>Descricao</th>
      <th>Datainicio</th>
      <th>Datafim</th>
      <th>Curriculo</th>
      <th>Aluno</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @experiencia.each do |experiencium| %>
      <tr>
        <td><%= experiencium.empresa %></td>
        <td><%= experiencium.cargo %></td>
        <td><%= experiencium.descricao %></td>
        <td><%= experiencium.dataInicio %></td>
        <td><%= experiencium.dataFim %></td>
        <td><%= experiencium.curriculo_id %></td>
        <td><%= experiencium.aluno_id %></td>
        <td><%= link_to 'Show', experiencium %></td>
        <td><%= link_to 'Edit', edit_experiencium_path(experiencium) %></td>
        <td><%= link_to 'Destroy', experiencium, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Experiencium', new_experiencium_path %>

app/views/experiencia/new.html.erb
<h1>New Experiencium</h1>

<%= render 'form', experiencium: @experiencium %>

<%= link_to 'Back', experiencia_path %>

app/views/experiencia/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Empresa:</strong>
  <%= @experiencium.empresa %>
</p>

<p>
  <strong>Cargo:</strong>
  <%= @experiencium.cargo %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @experiencium.descricao %>
</p>

<p>
  <strong>Datainicio:</strong>
  <%= @experiencium.dataInicio %>
</p>

<p>
  <strong>Datafim:</strong>
  <%= @experiencium.dataFim %>
</p>

<p>
  <strong>Curriculo:</strong>
  <%= @experiencium.curriculo_id %>
</p>

<p>
  <strong>Aluno:</strong>
  <%= @experiencium.aluno_id %>
</p>

<%= link_to 'Edit', edit_experiencium_path(@experiencium) %> |
<%= link_to 'Back', experiencia_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>